# yaml-language-server: $schema=./../../run.schema.json
# =============================================================================
# BENCHMARK GENERATION CONFIG
# =============================================================================
# The configuration used for benchmarks generation

# =============================================================================
# GLOBAL CONFIGURATION
# =============================================================================
global:
  workflow: "orchestrated_sales"
  default_provider: "openai"
  default_model: "gpt-6-luna"
  enable_logprobs: false
  enable_reasoning: false
  reasoning_effort: none
