# yaml-language-server: $schema=./../../run.schema.json
# =============================================================================
# MINIMAL RUN CONFIGURATION
# =============================================================================
# The minimal set of parameters that needs to be set for the ArcoConfig.from_yaml()
# to function properly

# =============================================================================
# GLOBAL CONFIGURATION
# =============================================================================
global:
  workflow: "strict_sales"
  token_stream_agents:
    - Analyzer
