from collections import defaultdict
from typing import TYPE_CHECKING

from rich.spinner import Spinner

if TYPE_CHECKING:
    from arco.core import Answer, Config, AgentType

# load singleton console
from arco.cli.console import console

from rich import box
from rich.status import Status
from rich.table import Table
from rich.live import Live
from rich.console import Group
from rich.panel import Panel
from rich.pretty import Pretty
from rich.rule import Rule
from rich.text import Text

import time
import math


class StatusDisplay:
    def __init__(self):
        self.status = ""
        self.init_time = time.time()
        self.node_start_time = None
        self.spinner = Spinner("dots")
        self.stopped = False

    def stop(self):
        self.stopped = True

    def set(self, status, start_time=None):
        self.status = status
        self.node_start_time = start_time

    def __rich__(self):
        if self.stopped:
            return ""

        text = f"[yellow]{self.status}[/yellow]"

        if self.node_start_time is not None:
            elapsed = time.time() - self.node_start_time
            text += f" [dim]Node time : {elapsed:.1f}s[/dim] "

        text += f"[dim]Total time : {time.time() - self.init_time:.1f}s[/dim]"

        self.spinner.update(text=text),
        return Panel(
            self.spinner,
            border_style="cyan",
        )

class StreamingDisplay(StatusDisplay):
    """
    Extends StatusDisplay with a live-updating panel showing the tokens
    accumulated so far for whichever node is currently streaming.
    """

    def __init__(self):
        super().__init__()
        self.active_node = None
        self.token_buffer = ""

    def add_token(self, node: str, content: str):
        if node != self.active_node:
            self.active_node = node
            self.token_buffer = ""
        self.token_buffer += content

    def clear_tokens(self):
        self.active_node = None
        self.token_buffer = ""

    def __rich__(self):
        if self.stopped:
            return ""
        text = f"[yellow]{self.status}[/yellow]"
        if self.node_start_time is not None:
            elapsed = time.time() - self.node_start_time
            text += f" [dim]Node time : {elapsed:.1f}s[/dim] "
        text += f"[dim]Total time : {time.time() - self.init_time:.1f}s[/dim]"
        self.spinner.update(text=text)

        panel = Panel(self.spinner, border_style="cyan")
        if self.token_buffer:
            token_panel = Panel(
                Text(self.token_buffer),
                title=f"[dim]{self.active_node} (streaming)[/dim]",
                border_style="dim cyan",
            )
            return Group(panel, token_panel)
        return panel

def streaming_agent_visualizer(events: Generator[str, Any], verbose=False, show_plot=False) -> State:
    """
    Visualizes generated updates produced by the agent.run() generator,
    including token-level streaming output.
    :param events: The events generated by the agent run
    :param verbose: Whether if we want verbose visualization or not
    :return: The final resulting state
    """
    status = StreamingDisplay()
    last_state = None
    with Live(status, refresh_per_second=8, screen=False) as live:
        energy_dict: dict = {}
        for update in events:
            event_type = update["event"]
            if event_type == "started":
                live.console.print(Panel(f"[bold cyan]Agent Run Started[/bold cyan]\n[dim]ID: {update['run_id']}[/dim]",
                                         border_style="blue"))
                status.set("Started the graph execution ")
            elif event_type == "cache":
                value = update["value"]
                if value == "search":
                    status.set("Searching cached runs")
                elif value == "hit":
                    live.console.print(Panel(f"[dim]Cache hit[/dim]", border_style="dim"))
                elif value == "miss":
                    live.console.print(Panel(f"[dim]Cache miss[/dim]", border_style="dim"))
                elif value == "store":
                    status.set("Storing results to cache ")
                elif value == "store_completed":
                    live.console.print(Panel(f"[dim]Successfully stored in cache[/dim]", border_style="dim"))
            elif event_type == "node_started":
                start_time = time.time()
                status.set(f"{update['node']} is running ", start_time)
            elif event_type == "token":
                status.add_token(update["node"], update["content"])
            elif event_type == "node_finished":
                status.clear_tokens()
                last_state = update["state"]
                last_answer: Answer = last_state.get_last_answer()
                status.set(f"{last_answer.agent_id.value} ended its run ")
                live.console.print(generate_answer_panel(answer=last_answer, verbose=verbose))
            elif event_type == "codecarbon":
                energy_dict = update["energy_dict"]
            elif event_type == "completed":
                status.stop()
                live.console.print(Panel(
                    f"[bold cyan]Agent Run Completed[/bold cyan]\n[dim]Total run time : {update['state'].global_profiling_data.total_time}s[/dim]",
                    border_style="blue"))
            elif event_type == "error":
                live.console.print(Panel(f"[bold red]Error[/bold red]\n[dim]{update['message']}[/dim]",
                                         border_style="red"))
    if energy_dict:
        console.print(_energy_impact_panel(energy_dict))
    if not last_state:
        status.stop()
        live.console.print(Panel(
            f"[bold red]Agent Run Completed[/bold red]\n[dim]No output has been produced[/dim]",
            border_style="red"))
        return None
    vis_answer: Answer | None = last_state.get_last_answer(AgentType.VISUALIZER)
    ret_answer: Answer | None = last_state.get_last_answer(AgentType.RETRIEVER)
    if show_plot and vis_answer and vis_answer.code and "plt" in vis_answer.code and ret_answer and ret_answer.data_df is not None:
        try:
            visualize_chart(ret_answer.data_df, vis_answer.chart_config, vis_answer.code)
        except Exception as e:
            console.print(f"[bold red]Error[/bold red]: couldn't execute visualization code\n{e}")
            console.print(Rule(title="[bold red]Execution Failed[/bold red]", style="red"))
            return last_state
    return last_state


def _generate_answer_subtitle(answer: Answer) -> str:
    conf = answer.agent_config
    subtitle_elements = []
    if conf.n > 1:
        idx = {"temperature": 0, "top_p": 1, "top_k": 2}[conf.bon_parameter]
        varying_vals = [p[idx] for p in conf.get_candidate_params()]
        subtitle_elements.append(f"Best-of-{conf.n} on {conf.bon_parameter}({varying_vals})")
        if answer.evaluation and answer.evaluation.success:
            subtitle_elements.append(f"Eval : {round(answer.evaluation.score, 3)}")
        else:
            subtitle_elements.append("Eval : none")
    else:
        subtitle_elements.append(f"Temp: {round(answer.agent_config.get_candidate_params()[0][0], 3)}")
    if answer.gt_evaluation and answer.gt_evaluation.success:
        subtitle_elements.append(f"GT-Eval : {round(answer.gt_evaluation.score, 3)}")
    if conf.cot_n > 1: subtitle_elements.append(f"CoT : {conf.cot_n}")
    return "[dim]" + ", ".join(subtitle_elements) + "[/dim]"


def _generate_discarded_answer_panel(answer: Answer) -> Panel:
    return Panel(
        renderable=answer.message,
        title=f"[dim cyan]Discarded[/dim cyan]",
        subtitle=_generate_answer_subtitle(answer),
        subtitle_align="right",
        border_style="dim",
        expand=True,
    )

def generate_answer_panel(answer: Answer, verbose: bool) -> Panel:
    # Build the main panel
    group_elements = [answer.message]
    if verbose and answer.agent_config:
        # Create a subpanel for the configs
        config_subpanel = Panel(
            Pretty(answer.agent_config, max_length=2, max_depth=2, indent_size=2),
            title="[dim]Config[/dim]",
            title_align="left",
            border_style="dim"
        )

        # Create a subpanel for discarded answers
        if answer.agent_config.n > 1:
            discarded_bon_subpanel = [
                _generate_discarded_answer_panel(discarded_answer) for discarded_answer in
                (answer.discarded_bon_answers if answer.discarded_bon_answers else [])
            ]
            group_elements += discarded_bon_subpanel

        # Subpanel for gt eval
        if answer.gt_evaluation is not None:
            gt_eval_subpanel = Panel(
                f"Ground Truth Evaluation: {answer.gt_evaluation.score}",
                title="[dim]GT Evaluation[/dim]",
                title_align="left",
                border_style="dim"
            )
            group_elements += [gt_eval_subpanel]

        # Subpanel for best of n eval
        if answer.evaluation is not None:
            eval_subpanel = Panel(
                f"Evaluation: {answer.evaluation.score}",
                title="[dim]Evaluation Step[/dim]",
                title_align="left",
                border_style="dim"
            )
            group_elements += [eval_subpanel]

        # Subpanel for perplexity and ARCO evaluation
        if answer.__getattribute__(
                'perplexity') is not None:
            arco_subpanel = Panel(
                f"Final perplexity: {answer.perplexity}\nBudget controller choice: {answer.budget_controller_choice}",
                title="[dim]ARCO evaluations[/dim]",
                title_align="left",
                border_style="dim"
            )
            group_elements += [arco_subpanel]

        # Subpanel for error messages
        if answer.error:
            error_subpanel = Panel(
                answer.error,
                title="[red]Error Message[/red]",
                title_align="left",
                border_style="red"
            )
            group_elements += [error_subpanel]

        if answer.logprobs and isinstance(answer.logprobs, list):
            colored_text = Text()

            for token, logprob in answer.logprobs:
                try:
                    token_ppl = math.exp(-logprob)
                except OverflowError:
                    token_ppl = float('inf')
                if token_ppl < 1.2: style = "bold green"
                elif token_ppl < 5.0: style = "yellow"
                else: style = "bold red"
                colored_text.append(token, style=style)

            perplexity_subpanel = Panel(
                colored_text,
                title="[dim]Token Perplexity Analysis[/dim]",
                title_align="left",
                subtitle="[bold green]■ <1.2 (High)[/bold green] [yellow]■ <5.0 (Mid)[/yellow] [bold red]■ ≥5.0 (Low Confidence)[/bold red]",
                subtitle_align="right",
                border_style="dim",
                expand=True
            )
            group_elements += [perplexity_subpanel]

        if answer.profiling_data:
            p = answer.profiling_data
            table = Table.grid(padding=(0, 2))
            table.add_column(style="cyan")
            table.add_column(justify="right")
            rows = [
                ("Total time", f"{p.total_time:.2f} s" if p.total_time is not None else "-"),
                ("LLM time", f"{p.llm_time:.2f} s" if p.llm_time is not None else "-"),
                ("Energy", f"{p.energy_consumed_kwh:.6f} kWh" if p.energy_consumed_kwh is not None else "-"),
                ("CPU", f"{p.cpu_energy_kwh:.6f} kWh" if p.cpu_energy_kwh is not None else "-"),
                ("GPU", f"{p.gpu_energy_kwh:.6f} kWh" if p.gpu_energy_kwh is not None else "-"),
                ("RAM", f"{p.ram_energy_kwh:.6f} kWh" if p.ram_energy_kwh is not None else "-"),
                ("CO₂", f"{p.emissions_kg_co2:.6f} kg" if p.emissions_kg_co2 is not None else "-"),
            ]
            for k, v in rows:
                table.add_row(k, v)
            profiling_subpanel = Panel(
                table,
                title="[dim]Profiling[/dim]",
                title_align="left",
                border_style="dim",
            )
            group_elements.append(profiling_subpanel)

        group_elements += [config_subpanel]
        content = Group(*group_elements)

    else:
        content = answer.message

    return Panel(
        renderable=content,
        title=f"[bold cyan]{answer.agent_id.value}[/bold cyan]",
        subtitle=_generate_answer_subtitle(answer),
        subtitle_align="right",
        border_style="green",
        expand=True,
    )


def _compact_answer_panel(answer: Answer) -> Panel:
    metrics = []

    if answer.evaluation and answer.evaluation.success:
        metrics.append(
            f"[cyan]Eval[/cyan] {answer.evaluation.score:.3f}"
        )
    if answer.gt_evaluation and answer.gt_evaluation.success:
        metrics.append(
            f"[green]GT[/green] {answer.gt_evaluation.score:.3f}"
        )
    if getattr(answer, "perplexity", None) is not None:
        metrics.append(
            f"[yellow]PPL[/yellow] {answer.perplexity:.2f}"
        )
    if answer.agent_config.cot_n > 1:
        metrics.append(
            f"[magenta]CoT[/magenta] {answer.agent_config.cot_n}"
        )
    content = " • ".join(metrics)
    if not content:
        content = "[dim]Completed[/dim]"
    return Panel(
        content,
        title=f"[bold cyan]{answer.agent_id.value}[/bold cyan]",
        border_style="cyan",
        expand=False,
    )


def _energy_impact_panel(energy_dict: dict[str, Any]) -> Panel:
    """Pretty prints CodeCarbon metrics from a structured energy_dict."""
    if not energy_dict:
        return Panel("No energy dict")

    ed = energy_dict
    # Extract metrics using your exact dictionary keys
    emissions = ed.get("emissions_kg_co2", 0.0)
    total_energy = ed.get("energy_consumed_kwh", 0.0)
    duration = ed.get("duration_sec", 0.0)

    cpu_power = ed.get("cpu_power_w", 0.0)
    cpu_energy = ed.get("cpu_energy_kwh", 0.0)

    gpu_power = ed.get("gpu_power_w", 0.0)
    gpu_energy = ed.get("gpu_energy_kwh", 0.0)

    ram_energy = ed.get("ram_energy_kwh", 0.0)

    # Build a grid for formatting
    grid = Table.grid(expand=True)
    grid.add_column(style="bold green", width=22)
    grid.add_column(style="cyan")

    grid.add_row("🌱 Carbon Footprint:", f"{emissions:.6f} kg CO₂eq")
    grid.add_row("⚡ Total Energy:", f"{total_energy:.6f} kWh")
    grid.add_row("⏱️ Duration:", f"{duration:.2f} seconds")
    grid.add_row("", "")  # Spacer
    grid.add_row("💻 CPU Core:", f"{cpu_power:.2f} W  ({cpu_energy:.6f} kWh)")
    if gpu_power > 0 or gpu_energy > 0:
        grid.add_row("🎮 GPU Core:", f"{gpu_power:.2f} W  ({gpu_energy:.6f} kWh)")
    grid.add_row("💾 RAM Overhead:", f"Pooled  ({ram_energy:.6f} kWh)")

    # Render unified layout
    return Panel(grid,
                 title="[bold green]📊 Codecarbon Report Summary[/bold green]",
                 border_style="green",
                 padding=(1, 2)
                 )


def print_benchmark_header(name: str, description: str, changes: dict[str, Any]) -> None:
    """Print a rich panel summarizing the benchmark run's name, description, and changes."""
    header = Text(f"Benchmark run : {name}", style="bold cyan", justify="center")

    body = Table.grid(padding=(0, 1))
    body.add_column(justify="right", style="bold dim")
    body.add_column()
    body.add_row("Description:", description or "[dim italic]none provided[/dim italic]")

    if changes:
        changes_table = Table(
            title="Overrides", show_header=True, header_style="bold magenta",
            box=box.SIMPLE_HEAVY, expand=False
        )
        changes_table.add_column("Agent", style="bold yellow")
        changes_table.add_column("Parameter", style="cyan")
        changes_table.add_column("Value", style="green")

        for agent_name, params in changes.items():
            if isinstance(params, dict):
                first = True
                for param, value in params.items():
                    changes_table.add_row(
                        agent_name if first else "",
                        param,
                        str(value)
                    )
                    first = False
            else:
                changes_table.add_row(agent_name, "-", str(params))
    else:
        changes_table = Text("No overrides — running with defaults.", style="dim italic")

    body.add_row("Changes:", changes_table)

    console.print(Panel(
        body,
        title=header,
        border_style="blue",
        box=box.ROUNDED,
        padding=(1, 2)
    ))

def agent_events_visualizer(events: Generator[str, Any], verbose=False, show_plot=False) -> State:
    """
    Visualizes generated updates produced by the agent.run() generator.
    :param events: The events generated by the agent run
    :param verbose: Whether if we want verbose visualization or not
    :return: The final resulting state
    """
    status = StatusDisplay()
    last_state = None

    with Live(status, refresh_per_second=8, screen=False) as live:
        energy_dict: dict = {}
        for update in events:
            event_type = update["event"]
            if event_type == "started":
                live.console.print(Panel(f"[bold cyan]Agent Run Started[/bold cyan]\n[dim]ID: {update["run_id"]}[/dim]",
                                         border_style="blue"))
                status.set("Started the graph execution ")
            elif event_type == "cache":
                value = update["value"]
                if value == "search":
                    status.set("Searching cached runs")
                elif value == "hit":
                    live.console.print(Panel(f"[dim]Cache hit[/dim]",
                                             border_style="dim"))
                elif value == "miss":
                    live.console.print(Panel(f"[dim]Cache miss[/dim]",
                                             border_style="dim"))
                elif value == "store":
                    status.set("Storing results to cache ")
                elif value == "store_completed":
                    live.console.print(Panel(f"[dim]Successfully stored in cache[/dim]",
                                             border_style="dim"))
            elif event_type == "node_started":
                start_time = time.time()
                status.set(f"{update['node']} is running ", start_time)
            elif event_type == "node_finished":
                last_state = update["state"]
                last_answer: Answer = last_state.get_last_answer()
                status.set(f"{last_answer.agent_id.value} ended its run ")
                live.console.print(generate_answer_panel(answer=last_answer, verbose=verbose))
            elif event_type == "codecarbon":
                energy_dict = update["energy_dict"]
            elif event_type == "completed":
                status.stop()
                live.console.print(Panel(
                    f"[bold cyan]Agent Run Completed[/bold cyan]\n[dim]Total run time : {update["state"].global_profiling_data.total_time}s[/dim]",
                    border_style="blue"))
            elif event_type == "error":
                live.console.print(Panel(f"[bold red]Error[/bold red]\n[dim]{update["message"]}[/dim]",
                                         border_style="red"))

    if energy_dict:
        console.print(_energy_impact_panel(energy_dict))

    # Fallback when model fails completely
    if not last_state:
        status.stop()
        live.console.print(Panel(
            f"[bold red]Agent Run Completed[/bold red]\n[dim]No output has been produced[/dim]",
            border_style="red"))
        return None

    from arco.core import AgentType
    vis_answer: Answer | None = last_state.get_last_answer(AgentType.VISUALIZER)
    ret_answer: Answer | None = last_state.get_last_answer(AgentType.RETRIEVER)
    if show_plot and vis_answer and vis_answer.code and "plt" in vis_answer.code and ret_answer and ret_answer.data_df is not None:
        try:
            visualize_chart(ret_answer.data_df, vis_answer.chart_config, vis_answer.code)
        except Exception as e:
            console.print(f"[bold red]Error[/bold red]: couldn't execute visualization code\n{e}")
            console.print(Rule(title="[bold red]Execution Failed[/bold red]", style="red"))
            return last_state

    return last_state


def compact_agent_events_visualizer(events) -> State:
    status = StatusDisplay()

    with Live(status, refresh_per_second=8, screen=False) as live:
        last_state = None
        for update in events:
            event_type = update["event"]
            if event_type == "started":
                status.set("Starting run")
            elif event_type == "node_started":
                status.set(f"{update['node']}", time.time())
            elif event_type == "node_finished":
                last_state = update["state"]
                answer = last_state.get_last_answer()
                agent = answer.agent_id.value
                status.set(f"{agent} completed")
            elif event_type == "completed":
                status.stop()

    return last_state

from collections import defaultdict
from statistics import mean

PROFILE_FIELDS = [
    "total_time",
    "llm_time",
    "energy_consumed_kwh",
    "cpu_energy_kwh",
    "gpu_energy_kwh",
    "ram_energy_kwh",
    "emissions_kg_co2",
]


def _avg(values: list[float | None]) -> float:
    values = [v for v in values if v is not None]
    return mean(values) if values else 0.0


def show_evaluation_summary(summary: EvaluationSummary):
    grouped = defaultdict(
        lambda: {
            "ppl": [],
            "score": [],
            **{field: [] for field in PROFILE_FIELDS},
        }
    )

    # Aggregate
    for agent, ppl, score, profiling in zip(
        summary.agents,
        summary.ppls,
        summary.scores,
        summary.profiling_datas,
    ):
        g = grouped[agent]
        g["ppl"].append(ppl)
        g["score"].append(score)

        for field in PROFILE_FIELDS:
            g[field].append(getattr(profiling, field))

    # Table
    table = Table(title="Evaluation Summary")

    table.add_column("Agent")
    table.add_column("#", justify="right")
    table.add_column("Avg PPL", justify="right")
    table.add_column("Avg Score", justify="right")
    table.add_column("Time (s)", justify="right")
    table.add_column("LLM (s)", justify="right")
    table.add_column("Energy (Wh)", justify="right")
    table.add_column("CPU (Wh)", justify="right")
    table.add_column("GPU (Wh)", justify="right")
    table.add_column("RAM (Wh)", justify="right")
    table.add_column("CO₂ (gCO₂)", justify="right")

    for agent, values in grouped.items():
        table.add_row(
            agent.value,
            str(len(values["ppl"])),
            f"{_avg(values['ppl']):.2f}",
            f"{_avg(values['score']):.2f}",
            f"{_avg(values['total_time']):.2f}",
            f"{_avg(values['llm_time']):.2f}",
            f"{_avg(values['energy_consumed_kwh'])*1000:.3f}",
            f"{_avg(values['cpu_energy_kwh'])*1000:.3f}",
            f"{_avg(values['gpu_energy_kwh'])*1000:.3f}",
            f"{_avg(values['ram_energy_kwh'])*1000:.3f}",
            f"{_avg(values['emissions_kg_co2'])*1000:.4f}",
        )

    console.print(table)

    # Timeline
    timeline = []

    for agent, ppl, score in zip(summary.agents, summary.ppls, summary.scores):
        color = (
            "green" if score >= 0.9 else
            "yellow" if score >= 0.7 else
            "red"
        )

        t = Text()
        t.append("█", style=color)
        t.append(f"{agent.value[:3]}({ppl:.2f},{score:.2f})")
        timeline.append(t)

    console.print(
        Panel(
            Text(" → ").join(timeline),
            title="Trace Summary",
        )
    )

    console.print(
        f"Completion: [bold cyan]{summary.completion_percentage:.1%}[/]"
    )

def print_config_table(config: Config, verbose: bool | None = None):
    """Helper to render a consistent Rich tables."""
    configs_to_show = {f.name: getattr(config, f.name) for f in config.__dataclass_fields__.values()}
    configs_to_show.pop("agent_configs")

    # Visualize run configuration
    params_list = [
        *[(key, value) for key, value in configs_to_show.items()],
    ]
    if verbose is not None:
        params_list.append(("verbose", verbose))
    table = Table(box=box.ROUNDED)
    table.add_column("Parameter", style="cyan", no_wrap=True)
    table.add_column("Current Value", style="white")
    for key, value in params_list:
        table.add_row(key, str(value))
    console.print(table)


def print_workflow(workflow: Workflow):
    console.print(Panel(
        str(workflow),
        title="Selected Workflow",
        title_align="center",
    ))

def visualize_chart(df, chart_config, code):
    with Status("Waiting for image to render", spinner="dots", refresh_per_second=8) as status:
        import matplotlib
        for backend in ("TkAgg", "Qt5Agg", "GTK3Agg"):
            try:
                matplotlib.use(backend)
                import matplotlib.pyplot as plt
                break
            except ImportError:
                plt = None

        if plt is None:
            print(
                "No interactive backend available. Install one of: python3-tkinter (system), PyQt5 (pip), or PyGObject (pip)")
            return

        namespace = {
            "data_df": df,
            "config": chart_config,
            "plt": plt,
            "pd": __import__("pandas"),
            "np": __import__("numpy"),
        }
        status.update("Waiting for visualization window to close")
        exec(code, namespace)  # noqa: S102
