import time
from collections.abc import Generator
from typing import TYPE_CHECKING, Any

from rich.live import Live
from rich.panel import Panel
from rich.text import Text

from arco.cli.viz.panels import (
    render_answer,
    render_answer_verbose,
    render_streamed_output,
)
from arco.cli.viz.status import RunStatusPanel

if TYPE_CHECKING:
    from arco.core.answer import Answer
    from arco.core.state import State


def _format_tool_parameters(parameters: Any) -> str:
    """Format tool arguments as a compact, readable call signature."""
    if isinstance(parameters, dict):
        return ", ".join(f"{key}={value!r}" for key, value in parameters.items())
    return repr(parameters)


def display_workflow_event(update: dict[str, Any], *, verbose: bool = False) -> None:
    """Render one workflow event in a frontend-controlled execution loop.

    Benchmark and benchmark-generation services forward neutral workflow
    events; this function keeps Rich presentation in the CLI layer.
    """
    event_type = update.get("event")
    if event_type == "node_started":
        if verbose:
            from arco.cli.console import console

            console.print(f"[dim]Starting {update.get('node', 'agent')}…[/dim]")
    elif event_type == "node_finished":
        from arco.cli.console import console

        state = update.get("state")
        answer = state.get_last_answer() if state is not None else None
        if answer is not None:
            console.print(
                render_answer_verbose(answer) if verbose else render_answer(answer)
            )
            if not verbose:
                console.print()
    elif event_type == "error":
        from arco.cli.console import console

        console.print(f"[red]✗[/red] {update.get('message', 'Workflow error')}")


def display_workflow_compact(events: Generator[dict[str, Any]]) -> State | None:
    status = RunStatusPanel(compact=True)

    with Live(status, refresh_per_second=8, screen=False):
        last_state = None
        for update in events:
            event_type = update["event"]
            if event_type == "started":
                status.set("Starting run")
            elif event_type == "node_started":
                status.set(f"{update['node']}", time.time())
            elif event_type == "node_finished":
                last_state = update["state"]
                answer = last_state.get_last_answer()
                agent = answer.agent_id
                status.set(f"{agent} completed")
            elif event_type == "completed":
                status.stop()

    return last_state


def display_workflow(events: Generator[dict[str, Any]], verbose=False) -> State | None:
    """
    Visualizes generated updates produced by the agent.run() generator.
    :param events: The events generated by the agent run
    :param verbose: Whether if we want verbose visualization or not
    :return: The final resulting state
    """
    # Keep non-streaming progress minimal; token-streamed output is rendered
    # in the live status view and preserved when the agent completes.
    status = RunStatusPanel(compact=True)
    last_state = None
    streamed_nodes: set[str] = set()

    live = Live(status, refresh_per_second=8, screen=False)
    live.__enter__()

    for update in events:
        event_type = update["event"]
        if event_type == "check_connection":
            status.set("Checking models")
        elif event_type == "started":
            status.set("Starting")
        elif event_type == "node_started":
            start_time = time.time()
            node = update["node"]
            status.clear_activity()
            status.set(f"{node}", start_time)
            status.active_node = node
        elif event_type == "token":
            node = str(update.get("node", "agent"))
            content = update.get("content", "")
            if content:
                status.active_node = node
                status.append_stream(content)
                streamed_nodes.add(node)
        elif event_type == "agent_progress":
            agent = str(update.get("agent", "agent"))
            message = update.get("message") or "Working"
            if update.get("kind") == "state":
                status.set_state(f"{agent} · {message}")
            elif update.get("kind") == "tool_started":
                event_data = update.get("data") or {}
                tool = event_data.get("tool")
                parameters = event_data.get("args")
                message = update.get("message") or tool or "Tool started"
                if parameters is not None:
                    parameter_text = _format_tool_parameters(parameters)
                    if len(parameter_text) > 500:
                        parameter_text = parameter_text[:497] + "..."
                    message = f"{message}({parameter_text})"
                status.append_tool_event(
                    Text("⚙ ", style="bold yellow")
                    + Text(agent, style="bold cyan")
                    + Text(f" · {message}", style="yellow")
                )
        elif event_type == "node_finished":
            streamed_output = status.stream_buffer
            tool_events = list(status.tool_events)
            status.clear_activity()
            last_state = update["state"]
            last_answer: Answer = last_state.get_last_answer()
            agent_name = str(last_answer.agent_id)
            was_streamed = agent_name in streamed_nodes

            heading_printed = False
            if tool_events:
                live.console.print(
                    Text("✓ ", style="bold green") + Text(agent_name, style="bold cyan")
                )
                live.console.print()
                for tool_event in tool_events:
                    live.console.print(tool_event)
                live.console.print()
                heading_printed = True

            if streamed_output and was_streamed:
                if not heading_printed:
                    live.console.print(
                        Text("✓ ", style="bold green")
                        + Text(agent_name, style="bold cyan")
                    )
                    live.console.print()
                live.console.print(render_streamed_output(streamed_output))
                if verbose:
                    live.console.print(
                        render_answer_verbose(
                            last_answer,
                            include_message=False,
                            include_agent=False,
                        )
                    )
                elif last_answer.error or last_answer.agent_output.get("image_path"):
                    live.console.print(
                        render_answer(
                            last_answer,
                            include_message=False,
                            include_agent=False,
                        )
                    )
            elif tool_events:
                live.console.print(
                    render_answer_verbose(
                        last_answer,
                        include_agent=False,
                    )
                    if verbose
                    else render_answer(last_answer, include_agent=False)
                )
            else:
                live.console.print(
                    render_answer_verbose(last_answer)
                    if verbose
                    else render_answer(last_answer)
                )
            if not verbose:
                live.console.print()

            status.set(f"{last_answer.agent_id} ended its run ")
        elif event_type == "codecarbon":
            pass
        elif event_type == "completed":
            status.stop()
            total_time = update["state"].global_profiling_data.total_time
            if verbose:
                live.console.print(
                    Panel(
                        f"[bold cyan]Agent Run Completed[/bold cyan]\n[dim]Total run time : {
                            total_time:.2f}s[/dim]"
                        if total_time is not None
                        else "[bold cyan]Agent Run Completed[/bold cyan]",
                        border_style="blue",
                    )
                )
            else:
                completed = Text()
                completed.append("✓ ", style="bold green")
                completed.append("Completed", style="bold")
                if total_time is not None:
                    completed.append(f"  {total_time:.2f}s", style="dim")
                completed.append("\n")
                live.console.print(completed)
        elif event_type == "error":
            if verbose:
                live.console.print(
                    Panel(
                        f"[bold red]Error[/bold red]\n[dim]{update['message']}[/dim]",
                        border_style="red",
                    )
                )
            else:
                live.console.print(Text(f"✗ {update['message']}", style="bold red"))
                live.console.print()

    # Fallback when model fails completely
    if not last_state:
        status.stop()
        if verbose:
            live.console.print(
                Panel(
                    "[bold red]Agent Run Failed[/bold red]\n[dim]No output produced[/dim]",
                    border_style="red",
                )
            )
        else:
            live.console.print(Text("✗ No output produced", style="bold red"))
        return None

    return last_state
