import time
from typing import Any, Generator, TYPE_CHECKING

from rich.live import Live
from rich.panel import Panel

from arco.cli.console import console
from arco.cli.viz.panels import render_answer, render_energy_impact_panel
from arco.cli.viz.status import RunStatusPanel

if TYPE_CHECKING:
    from arco.core import Answer, State


def display_workflow_compact(events: Generator[str, Any]) -> State:
    status = RunStatusPanel()

    with Live(status, refresh_per_second=8, screen=False) as live:
        last_state = None
        for update in events:
            event_type = update["event"]
            if event_type == "started":
                status.set("Starting run")
            elif event_type == "node_started":
                status.set(f"{update['node']}", time.time())
            elif event_type == "node_finished":
                last_state = update["state"]
                answer = last_state.get_last_answer()
                agent = answer.agent_id.value
                status.set(f"{agent} completed")
            elif event_type == "completed":
                status.stop()

    return last_state


def display_workflow(events: Generator[str, Any], verbose=False) -> State:
    """
    Visualizes generated updates produced by the agent.run() generator.
    :param events: The events generated by the agent run
    :param verbose: Whether if we want verbose visualization or not
    :return: The final resulting state
    """
    status = RunStatusPanel()
    last_state = None

    with Live(status, refresh_per_second=8, screen=False) as live:
        energy_dict: dict = {}
        for update in events:
            event_type = update["event"]
            if event_type == "started":
                status.set("Started the graph execution ")
            elif event_type == "node_started":
                start_time = time.time()
                status.set(f"{update['node']} is running ", start_time)
            elif event_type == "node_finished":
                last_state = update["state"]
                last_answer: Answer = last_state.get_last_answer()
                status.set(f"{last_answer.agent_id.value} ended its run ")
                live.console.print(render_answer(answer=last_answer, verbose=verbose))
            elif event_type == "codecarbon":
                energy_dict = update["energy_dict"]
            elif event_type == "completed":
                status.stop()
                live.console.print(Panel(
                    f"[bold cyan]Agent Run Completed[/bold cyan]\n[dim]Total run time : {update['state'].global_profiling_data.total_time}s[/dim]",
                    border_style="blue"))
            elif event_type == "error":
                live.console.print(Panel(f"[bold red]Error[/bold red]\n[dim]{update['message']}[/dim]",
                                         border_style="red"))

    if energy_dict:
        console.print(render_energy_impact_panel(energy_dict))

    # Fallback when model fails completely
    if not last_state:
        status.stop()
        live.console.print(Panel(
            f"[bold red]Agent Run Completed[/bold red]\n[dim]No output has been produced[/dim]",
            border_style="red"))
        return None

    return last_state
