import time
from collections.abc import Generator
from typing import TYPE_CHECKING, Any

from rich.live import Live
from rich.panel import Panel
from rich.text import Text

from arco.cli.viz.panels import (
    render_answer,
    render_answer_verbose,
)
from arco.cli.viz.status import RunStatusPanel

if TYPE_CHECKING:
    from arco.core import Answer, State


def display_workflow_compact(events: Generator[dict[str, Any]]) -> State | None:
    status = RunStatusPanel(compact=True)

    with Live(status, refresh_per_second=8, screen=False):
        last_state = None
        for update in events:
            event_type = update["event"]
            if event_type == "started":
                status.set("Starting run")
            elif event_type == "node_started":
                status.set(f"{update['node']}", time.time())
            elif event_type == "node_finished":
                last_state = update["state"]
                answer = last_state.get_last_answer()
                agent = answer.agent_id
                status.set(f"{agent} completed")
            elif event_type == "completed":
                status.stop()

    return last_state


def display_workflow(events: Generator[dict[str, Any]], verbose=False) -> State | None:
    """
    Visualizes generated updates produced by the agent.run() generator.
    :param events: The events generated by the agent run
    :param verbose: Whether if we want verbose visualization or not
    :return: The final resulting state
    """
    # Keep progress itself minimal in both modes; verbose details are shown
    # in the completed agent cards below.
    status = RunStatusPanel(compact=True)
    last_state = None

    live = Live(status, refresh_per_second=8, screen=False)
    live.__enter__()

    for update in events:
        event_type = update["event"]
        if event_type == "check_connection":
            status.set("Checking models")
        elif event_type == "started":
            status.set("Starting")
        elif event_type == "node_started":
            start_time = time.time()
            node = update["node"]
            status.set(node if not verbose else f"{node} is running ", start_time)
            status.active_node = node
        elif event_type == "node_finished":
            status.clear_stream()
            last_state = update["state"]
            last_answer: Answer = last_state.get_last_answer()
            live.console.print(
                render_answer_verbose(last_answer)
                if verbose
                else render_answer(last_answer)
            )
            if not verbose:
                live.console.print()

            status.set(f"{last_answer.agent_id} ended its run ")
        elif event_type == "codecarbon":
            pass
        elif event_type == "completed":
            status.stop()
            total_time = update["state"].global_profiling_data.total_time
            if verbose:
                live.console.print(
                    Panel(
                        f"[bold cyan]Agent Run Completed[/bold cyan]\n[dim]Total run time : {
                            total_time:.2f}s[/dim]"
                        if total_time is not None
                        else "[bold cyan]Agent Run Completed[/bold cyan]",
                        border_style="blue",
                    )
                )
            else:
                completed = Text()
                completed.append("✓ ", style="bold green")
                completed.append("Completed", style="bold")
                if total_time is not None:
                    completed.append(f"  {total_time:.2f}s", style="dim")
                live.console.print(completed)
        elif event_type == "error":
            if verbose:
                live.console.print(
                    Panel(
                        f"[bold red]Error[/bold red]\n[dim]{update['message']}[/dim]",
                        border_style="red",
                    )
                )
            else:
                live.console.print(Text(f"✗ {update['message']}", style="bold red"))
                live.console.print()

    # Fallback when model fails completely
    if not last_state:
        status.stop()
        if verbose:
            live.console.print(
                Panel(
                    "[bold red]Agent Run Failed[/bold red]\n[dim]No output produced[/dim]",
                    border_style="red",
                )
            )
        else:
            live.console.print(Text("✗ No output produced", style="bold red"))
        return None

    return last_state
