import base64
import io
import os
import sys
import time
from pathlib import Path

from arco.cli.console import console


def _terminal_capability() -> str | None:
    """Detect terminal image display capability.

    Returns:
        "kitty" for Kitty protocol, "iterm2" for iTerm2, or None for fallback.
    """
    if "KITTY_WINDOW_ID" in os.environ or os.environ.get("TERM") == "xterm-kitty":
        return "kitty"
    if os.environ.get("TERM_PROGRAM") == "iTerm.app":
        return "iterm2"
    return None


def _display_kitty(png_data: bytes):
    """Display PNG inline using Kitty's image protocol."""
    chunk = base64.b64encode(png_data).decode()
    sys.stdout.buffer.write(f"\x1b_Ga=T,f=100,m=0;{chunk}\x1b\\".encode())
    sys.stdout.buffer.write(b"\x1b_Ga=p,m=0\x1b\\\n")
    sys.stdout.flush()
    time.sleep(1)


def _display_iterm2(png_data: bytes):
    """Display PNG inline using iTerm2's imgcat protocol."""
    chunk = base64.b64encode(png_data).decode()
    sys.stdout.buffer.write(f"\x1b]1337;File=inline=1:{chunk}\x07\n".encode())
    sys.stdout.flush()
    time.sleep(1)


def execute_chart_code(df, chart_config, code, save_dir: str | None = None):
    """Render a matplotlib chart generated by the Visualizer agent.

    Uses a non-interactive Agg backend, captures the chart to a PNG buffer,
    and displays it inline when the terminal supports it (Kitty/iTerm2).
    Falls back to saving the chart to a file.
    """
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import numpy as np
        import pandas as pd
    except ImportError:
        console.print(
            "[yellow]matplotlib not available — skipping chart rendering[/yellow]"
        )
        return

    buf = io.BytesIO()

    namespace = {
        "data_df": df,
        "config": chart_config,
        "plt": plt,
        "pd": pd,
        "np": np,
        "buf": buf,
    }

    # Replace plt.show() with savefig to capture the output
    modified_code = code.replace(
        "plt.show()",
        "plt.savefig(buf, format='png', dpi=100, bbox_inches='tight'); plt.close()",
    )

    try:
        exec(modified_code, namespace)  # noqa: S102
    except Exception as e:
        console.print(f"[red]Chart rendering failed:[/red] {e}")
        return

    buf.seek(0)
    png_data = buf.getvalue()

    if not png_data:
        return

    # Try inline display
    cap = _terminal_capability()
    if cap == "kitty":
        _display_kitty(png_data)
    elif cap == "iterm2":
        _display_iterm2(png_data)
        print()  # iTerm2 needs a newline after the image
    else:
        # Fallback: save to file
        output_dir = Path(save_dir or "./output/charts")
        output_dir.mkdir(parents=True, exist_ok=True)
        title = chart_config.get("title", "chart") if chart_config else "chart"
        safe_title = "".join(c if c.isalnum() or c in " _-" else "_" for c in title)
        save_path = output_dir / f"{safe_title}.png"
        save_path.write_bytes(png_data)
        console.print(f"[dim]Chart saved to [cyan]{save_path}[/cyan][/dim]")
