# yaml-language-server: $schema=./../schema.json
# =============================================================================
# CACHE RUN CONFIGURATION
# =============================================================================
# Test config for caching for reading

global:
  schema: "../../data"
  prompt: "Do we sell more organic or inorganic products?"
  use_cache: true
  cache_mode: "r"
  save_dir: "./output"