# yaml-language-server: $schema=./../schema.json
# =============================================================================
# TEST CODECARBON OUTPUT
# =============================================================================
# Test config for the codecarbon integration

global:
  schema: "../../../data"
  prompt: "Show me the sales in Nov 2021"
  enable_codecarbon: true
  # Additional caching (not strictly needed for codecarbon)
  use_cache: true
  run_id: "codecarbon_test"
  cache_mode: "w"
  save_dir: "./output"
