# yaml-language-server: $schema=./../schema.json
# =============================================================================
# TEST GLOBAL CONFIGS
# =============================================================================
# Test config for the global section

global:
  schema: "../../../data"
  prompt: "Show me the sales in Nov 2021, with date as x and sales value as y"
  model: "gpt-5.4-nano"
  provider: "openai"
  orchestration_enabled: True
