# yaml-language-server: $schema=./../schema.json
# =============================================================================
# CACHE RUN CONFIGURATION
# =============================================================================
# Test config for caching for writes

global:
  schema: "../../../data"
  prompt: "Do we sell more organic or inorganic products?"
  use_cache: true
  run_id: "cache_test_run_id"
  cache_mode: "w"
  save_dir: "./output"

agents:
  Retriever:
    n: 2