# yaml-language-server: $schema=./../schema.json
# =============================================================================
# TEST PROVIDER-MODEL GLOBAL PARAMETERS
# =============================================================================
# Test for the provider and model parameters

global:
  workflow: "sales"
  prompt: "Show me the sales in Nov 2021, with date as x and sales value as y"
  default_provider: ollama
  default_model: phi3