# yaml-language-server: $schema=./../schema.json
# =============================================================================
# TEST AGENTS SECTION
# =============================================================================
# Test for the agents section

global:
  prompt: "Show me the sales in Nov 2021"
  visualization_goal: "Sales trend for Nov 2021, with date as x and sales value as y"
  schema: "../../data" # path to YAML schemas for the database relative to this config
  save_state: true

