# yaml-language-server: $schema=./../schema.json
# =============================================================================
# TEST PROVIDER-MODEL GLOBAL PARAMETERS
# =============================================================================
# Test for the provider and model parameters

global:
  prompt: "Show me the sales in Nov 2021"
  visualization_goal: "Sales trend for Nov 2021, with date as x and sales value as y"
  schema: "../../../data" # path to YAML schemas for the database relative to this config
  provider: ollama
  model: phi3