# yaml-language-server: $schema=./../schema.json
global:
  schema: "../../data"
  prompt: ""
  visualization_goal: ""
  orchestration_enabled: true
  enable_budget_controller: false

agents:
  Retriever:
    temp_min: 0.1
  Analyzer:
    temp_min: 0.1
  Visualizer:
    temp_min: 0.1
