# yaml-language-server: $schema=./../schema.json
# =============================================================================
# MINIMAL RUN CONFIGURATION
# =============================================================================
# The minimal set of parameters that needs to be set for the ArcoConfig.from_yaml()
# to function properly

# =============================================================================
# GLOBAL CONFIGURATION
# =============================================================================
global:
  workflow: "sales"
  prompt: "Show me the sales in Nov 2021, with date as x and sales value as y"