# yaml-language-server: $schema=./../schema.json
# =============================================================================
# MINIMAL RUN CONFIGURATION
# =============================================================================
# The minimal set of parameters that needs to be set for the ArcoConfig.from_yaml()
# to function properly

# =============================================================================
# GLOBAL CONFIGURATION
# =============================================================================
global:
  schema: "../../data" # path to YAML schemas for the database
  prompt: "Show me the sales in Nov 2021"
  visualization_goal: "Sales trend for Nov 2021, with date as x and sales value as y"