# yaml-language-server: $schema=./../schema.json
# =============================================================================
# ORCHESTRATED RUN CONFIGURATION
# =============================================================================
# The minimal set of parameters to run the orchestrated version of the agent

# =============================================================================
# GLOBAL CONFIGURATION
# =============================================================================
global:
  workflow: "planned_sales"